config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', as: 'tolk'
  devise_for :users,
             controllers: {
               registrations: 'auth/registrations',
               sessions: 'auth/sessions',
               confirmations: 'auth/confirmations',
               omniauth_callbacks: 'auth/omniauth_callbacks',
               invitations: 'auth/invitations'
             }

  devise_scope :user do
    get '/users/sign_up/success' => 'auth/registrations#success'
  end

  devise_scope :user do
    get '/teachers/sign_up' => 'auth/registrations#new_teacher'
    post '/teachers/sign_up' => 'auth/registrations#create_teacher'
  end

  if Wingzzz.config.kitchen_sink[:enabled]
    get '/kitchen-sink', to: 'kitchen_sink#index'
  end

  namespace :admin do
    resources :books do
      resource :epub
    end

    resources :users do
      post :unsubscribe, on: :member
    end

    resources :publishers

    resources :authors

    root to: 'books#index'
  end

  resources :books, only: %i[index show]

  scope module: 'account' do
    resource :account do
      post :unsubscribe, on: :member
      resource :settings
    end
  end

  resources :books do
    resource :book_session, only: %i[update]
  end

  resource :profile, only: %i[update]
  resolve('Profile') { %i[profile] }

  resource :subscription, only: %i[new create show]

  get 'subscription/new_school',
      to: 'subscriptions#new_school', as: 'new_school_subscription'
  post 'subscription/create_school',
       to: 'subscriptions#create_school', as: 'create_school_subscription'
  get 'subscriptions/teacher_options', to: 'subscriptions#teacher_options'

  root to: 'books#index'

  get 's3_files/*key', to: 's3_files#show', as: 's3_file'

  namespace :webhooks do
    post '/mollie/payment', to: 'mollie#payment'
    post '/mollie/subscription', to: 'mollie#subscription'
    get '/mollie/pay/:token', to: 'mollie#pay', as: 'mollie_payment_redirect'
  end
end

app/models/book.rb
require 'book_storage/local'
require 'book_storage/s3'

class Book < ApplicationRecord
  MAX_TITLE_ALLOWED = 255
  SLUG_SEPARATOR = '-'.freeze
  RANDOM_HEX_LENGTH = 4
  LAYOUTS = %w[two_pages single_page].freeze
  TRENDING_NOW_LIMIT = 5
  CURRENTLY_READING_LIMIT = 10
  RECENTLY_ADDED_LIMIT = 10

  enum reader: { default: 0, animated: 1 }, _prefix: true
  enum book_type: { regular: 0, narrated: 1, audio_only: 2 }

  acts_as_taggable_on :keywords

  belongs_to :publisher, optional: true
  has_many :book_sessions, dependent: :destroy
  # rubocop:disable Rails/HasAndBelongsToMany
  has_and_belongs_to_many :authors
  # rubocop:enable Rails/HasAndBelongsToMany
  validates :title, presence: true, length: { maximum: MAX_TITLE_ALLOWED }
  validates :slug, format: { without: /\s/ }
  validates :language,
            presence: true,
            inclusion: { in: I18n.available_locales.collect(&:to_s) }

  validates :layout, presence: true, inclusion: { in: LAYOUTS }
  validates :summary, length: { maximum: 2**10 }
  validates :trending_now_position,
            allow_nil: true, numericality: { greater_than: 0, less_than: 128 }

  before_create :set_slug
  before_validation :set_defaults

  mount_uploader :cover, BookCoverUploader
  mount_uploader :audio, BookAudioUploader

  class << self
    def trending_now(limit = TRENDING_NOW_LIMIT)
      where.not(trending_now_position: nil).order(:trending_now_position).limit(
        limit
      )
    end

    def currently_reading(profile, limit = CURRENTLY_READING_LIMIT)
      joins(:book_sessions).merge(
        BookSession.where(profile: profile).order(updated_at: :desc)
      )
        .limit(limit)
    end

    def recently_added(limit = RECENTLY_ADDED_LIMIT)
      order(created_at: :desc).limit(limit)
    end
  end

  def storage
    @storage ||=
      "BookStorage::#{Wingzzz.config.books[:storage]}".constantize.new(self)
  end

  private

  def set_slug
    self.slug ||= title.parameterize

    while self.class.where(slug: slug).exists?
      limit = MAX_TITLE_ALLOWED - (SLUG_SEPARATOR.length + RANDOM_HEX_LENGTH)
      self.slug =
        [title.first(limit).parameterize, randomhex].join(SLUG_SEPARATOR)
    end
  end

  def randomhex
    SecureRandom.hex(RANDOM_HEX_LENGTH / 2)
  end

  def set_defaults
    self.language ||= I18n.default_locale
    self.layout ||= 'two_pages'
  end
end

app/controllers/admin/books_controller.rb
module Admin
  class BooksController < Admin::ApplicationController
    include ApplicationHelper

    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include ApplicationHelper

  def index
    @mobile_reset = true
    set_search_results
    set_trending_now
    set_currently_reading
    set_recently_added
    set_book_collection
    set_book_types
  end

  def show
    @mobile_fixed = true
    @book = Book.find(params[:id]).decorate
    @book_session = BookSession.for(@book, current_profile)
  end

  private

  def filter_params
    params[:filters]&.slice(:q)
  end

  def profile_params
    params.fetch(:profile, {}).permit(:min_age_in_months, :max_age_in_months)
  end

  def set_trending_now
    @trending_now =
      Book.where(language: current_profile.content_language).trending_now
        .decorate
  end

  def set_currently_reading
    @currently_reading =
      Book.includes(:publisher, :authors).currently_reading(current_profile)
        .decorate
  end

  def set_recently_added
    @recently_added =
      Book.includes(:publisher, :authors).where(
        language: current_profile.content_language
      )
        .recently_added
        .decorate
  end

  def set_book_collection
    @book_collection = BookCollection.from_filters(nil, current_profile)
  end

  def set_search_results
    @search_results =
      BookCollection.from_filters(filter_params, current_profile)
  end

  def set_book_types
    @book_types = Book.book_types
  end
end

app/views/admin/books/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <th></th>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <th></th>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <td>
          <%= render(Books::CoverImageComponent.new(book: resource.decorate, width: 40, height: 52)) %>
        </td>
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                <%= render_field attribute %>
              </a>
            <% end -%>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/books/show.html.erb
<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <% if valid_action?(:edit) && show_action?(:edit, page.resource) %>
    <div class="mr-4">
      <%= link_to(
        t("edit_book").capitalize,
        [:edit, namespace, page.resource],
        class: "button",
      ) %>
    </div>

    <div class="mr-4">
      <%= link_to(
        t("edit_epub").upcase_first,
        edit_admin_book_epub_path(book_id: page.resource),
        class: "button",
      ) %>
    </div>
  <% end %>
</header>

<section class="main-content__body">
  <div class="flex">
    <div class="flex-1">
      <div class="relative h-full overflow-hidden">
        <dl>
          <% page.attributes.each do |attribute| %>
            <dt class="attribute-label" id="<%= attribute.name %>">
            <%= t(
              "helpers.label.#{resource_name}.#{attribute.name}",
              default: attribute.name.titleize,
            ) %>
            </dt>

            <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
                ><%= render_field attribute, page: page %></dd>
          <% end %>
        </dl>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="text-right">
      <div class="mb-2">
        <%= link_to book_path(page.resource), target: '_blank' do %>
          <div>
            <%= render(Books::CoverImageComponent.new(book: page.resource.decorate)) %>
          </div>
        <% end %>
      </div>
      <div>
        <div class="mb-2">
          <%= link_to book_path(page.resource), target: '_blank' do %>
            <div class="btn btn-secondary text-center">
              <%= t('preview').capitalize %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>