config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', as: 'tolk'
  devise_for :users,
             controllers: {
               registrations: 'auth/registrations',
               sessions: 'auth/sessions',
               confirmations: 'auth/confirmations',
               omniauth_callbacks: 'auth/omniauth_callbacks',
               invitations: 'auth/invitations'
             }

  devise_scope :user do
    get '/users/sign_up/success' => 'auth/registrations#success'
  end

  devise_scope :user do
    get '/teachers/sign_up' => 'auth/registrations#new_teacher'
    post '/teachers/sign_up' => 'auth/registrations#create_teacher'
  end

  if Wingzzz.config.kitchen_sink[:enabled]
    get '/kitchen-sink', to: 'kitchen_sink#index'
  end

  namespace :admin do
    resources :books do
      resource :epub
    end

    resources :users do
      post :unsubscribe, on: :member
    end

    resources :publishers

    resources :authors

    root to: 'books#index'
  end

  resources :books, only: %i[index show]

  scope module: 'account' do
    resource :account do
      post :unsubscribe, on: :member
      resource :settings
    end
  end

  resources :books do
    resource :book_session, only: %i[update]
  end

  resource :profile, only: %i[update]
  resolve('Profile') { %i[profile] }

  resource :subscription, only: %i[new create show]

  get 'subscription/new_school',
      to: 'subscriptions#new_school', as: 'new_school_subscription'
  post 'subscription/create_school',
       to: 'subscriptions#create_school', as: 'create_school_subscription'
  get 'subscriptions/teacher_options', to: 'subscriptions#teacher_options'

  root to: 'books#index'

  get 's3_files/*key', to: 's3_files#show', as: 's3_file'

  namespace :webhooks do
    post '/mollie/payment', to: 'mollie#payment'
    post '/mollie/subscription', to: 'mollie#subscription'
    get '/mollie/pay/:token', to: 'mollie#pay', as: 'mollie_payment_redirect'
  end
end

app/views/fields/has_many/_form.html.erb
<%#
# HasMany Form Partial

This partial renders an input element for has_many relationships.
By default, the input is a collection select box
that displays all possible records to associate with.
The collection select box supports multiple inputs,
and is augmented with [Selectize].

## Local variables:

- `f`:
  A Rails form generator, used to help create the appropriate input fields.
- `field`:
  An instance of [Administrate::Field::HasMany][1].
  Contains helper methods for displaying a collection select box.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Field/HasMany
[Selectize]: http://brianreavis.github.io/selectize.js
%>

<div class="field-unit__label">
  <%= f.label field.attribute, for: "#{f.object_name}_#{field.attribute_key}" %>
</div>
<div class="field-unit__field">
  <%= f.select(field.attribute_key, nil, {}, multiple: true) do %>
    <%= options_for_select(field.associated_resource_options, field.selected_options) %>
  <% end %>
</div>

app/views/fields/has_many/_index.html.erb
<%#
# HasMany Index Partial

This partial renders a has_many relationship,
to be displayed on a resource's index page.

By default, the relationship is rendered
as a count of how many objects are associated through the relationship.

## Local variables:

- `field`:
  An instance of [Administrate::Field::HasMany][1].
  A wrapper around the has_many relationship pulled from the database.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Field/HasMany
%>

<%= pluralize(field.data.size, field.attribute.to_s.humanize.downcase.singularize) %>

app/views/fields/has_many/_show.html.erb
<% if field.resources.any? && field.name == 'authors' %>
  <%= field.resources.map{ |resource| link_to resource.name, admin_author_path(resource.id) }.join(', ').html_safe %>
<% elsif field.resources.any? %>
  <% order = field.order_from_params(params.fetch(field.name, {})) %>
  <% page_number = params.fetch(field.name, {}).fetch(:page, nil) %>
  <%= render(
    "collection",
    collection_presenter: field.associated_collection(order),
    collection_field_name: field.name,
    page: page,
    resources: field.resources(page_number, order),
    table_title: field.name,
  ) %>
  <% if field.more_than_limit? %>
    <%= paginate field.resources(page_number), param_name: "#{field.name}[page]" %>
  <% end %>
<% else %>
  <%= t("administrate.fields.has_many.none", default: "–") %>
<% end %>