config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', as: 'tolk'
  devise_for :users,
             controllers: {
               registrations: 'auth/registrations',
               sessions: 'auth/sessions',
               confirmations: 'auth/confirmations',
               omniauth_callbacks: 'auth/omniauth_callbacks',
               invitations: 'auth/invitations'
             }

  devise_scope :user do
    get '/users/sign_up/success' => 'auth/registrations#success'
  end

  devise_scope :user do
    get '/teachers/sign_up' => 'auth/registrations#new_teacher'
    post '/teachers/sign_up' => 'auth/registrations#create_teacher'
  end

  if Wingzzz.config.kitchen_sink[:enabled]
    get '/kitchen-sink', to: 'kitchen_sink#index'
  end

  namespace :admin do
    resources :books do
      resource :epub
    end

    resources :users do
      post :unsubscribe, on: :member
    end

    resources :publishers

    resources :authors

    root to: 'books#index'
  end

  resources :books, only: %i[index show]

  scope module: 'account' do
    resource :account do
      post :unsubscribe, on: :member
      resource :settings
    end
  end

  resources :books do
    resource :book_session, only: %i[update]
  end

  resource :profile, only: %i[update]
  resolve('Profile') { %i[profile] }

  resource :subscription, only: %i[new create show]

  get 'subscription/new_school',
      to: 'subscriptions#new_school', as: 'new_school_subscription'
  post 'subscription/create_school',
       to: 'subscriptions#create_school', as: 'create_school_subscription'
  get 'subscriptions/teacher_options', to: 'subscriptions#teacher_options'

  root to: 'books#index'

  get 's3_files/*key', to: 's3_files#show', as: 's3_file'

  namespace :webhooks do
    post '/mollie/payment', to: 'mollie#payment'
    post '/mollie/subscription', to: 'mollie#subscription'
    get '/mollie/pay/:token', to: 'mollie#pay', as: 'mollie_payment_redirect'
  end
end

app/models/subscription.rb
# See: https://docs.mollie.com/payments/recurring
#
# This model serves as a state machine that tracks
# the status of the subscription.
# This makes it eas(y|ier) to do things as checking
# if a transition is allowed, creating Mollie objects
# at the right moment, etc.
class Subscription < ApplicationRecord
  include SubscriptionLifecycle

  RESOURCE_NOT_FOUND_ERROR_MSG =
    'Unable to retrieve a Mollie payment: %s'.freeze

  belongs_to :user

  delegate :mollie_customer_id, :mollie_customer_id=, to: :user

  class << self
    def find_by_mollie_payment!(payment_id)
      assert(payment_id)
      payment = get_mollie_payment(payment_id)
      get_decorated_subscription(payment)
    end

    private

    def assert(payment_id)
      return if payment_id.present?

      raise ActiveRecord::RecordNotFound,
            RESOURCE_NOT_FOUND_ERROR_MSG % 'Payment ID is not provided'
    end

    def get_mollie_payment(payment_id)
      Mollie::Payment.get(payment_id)
    rescue Mollie::ResourceNotFoundError => e
      raise ActiveRecord::RecordNotFound,
            RESOURCE_NOT_FOUND_ERROR_MSG % e.message
    end

    def get_decorated_subscription(mollie_payment)
      user = User.find(mollie_payment.metadata.wz_user_id)
      user.subscription.tap { |s| s.mollie_payment = mollie_payment }
    end
  end

  # Query methods:
  #
  def mollie_subscription
    @mollie_subscription ||=
      Mollie::Customer::Subscription.get(
        mollie_subscription_id,
        customer_id: user.mollie_customer_id
      )
  end

  def in_grace_period?
    grace_period_ends_on.nil? || grace_period_ends_on >= Date.current
  end

  def grace_period_ended?
    !in_grace_period?
  end

  def payment_canceled?
    !mollie_payment.paid? && !mollie_payment.open?
  end

  private

  def set_token
    loop do
      self.token = SecureRandom.urlsafe_base64
      break unless token_exists?
    end
  end

  def token_exists?
    self.class.where(token: token).exists?
  end

  def set_grace_period
    self.grace_period_ends_on = mollie_subscription.next_payment_date
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  respond_to :html
  skip_before_action :authenticate_subscription
  before_action :authenticate_teacher,
                only: %i[teacher_options new_school create_school]
  before_action :already_has_school_subscription, only: %i[new_school]
  before_action -> { @mobile_friendly = true }

  # There are only `new`/`create` actions, even if
  # the user is in the process of activating a subscription.
  # The subscription model ensures that an initialized subscription
  # can be used to continue activation.
  def new
    if current_user.subscription&.initialized?
      flash[:notice] = t('subscription_not_yet_activated')
    else
      flash.clear
    end
  end

  def teacher_options; end

  def new_school
    @school_subscription =
      SchoolSubscription.fill_billing_from_school current_user
  end

  def create_school
    school_subscription = setup_school_subscription

    if school_subscription.persisted?
      add_school_subscription_roles
      send_out_subscription_mails school_subscription
      flash[:notice] = 'successful signup'
      redirect_to new_user_invitation_url
    else
      redirect_to new_school_subscription_path
    end
  end

  def create
    subscription = current_user.subscribe
    redirect_to subscription.checkout_url
  end

  def show
    redirect_to root_url unless current_user.subscription&.pending?
  end

  private

  def setup_school_subscription
    school_subscription = SchoolSubscription.new(school_subscription_params)
    school_subscription.end_date = Time.now.utc.end_of_year
    school_subscription.save

    school_subscription
  end

  def add_school_subscription_roles
    current_user.add_role(:school_subscription_member)
    current_user.add_role(:school_subscription_owner)
  end

  def send_out_subscription_mails(school_subscription)
    UserMailer.with(user: current_user).activation_email_for_school_subscription
      .deliver_later
    UserMailer.with(
      user: current_user,
      email: Wingzzz.config.admin_email,
      school_subscription: school_subscription
    )
      .notification_email_about_school_subscription
      .deliver_later
  end

  def already_has_school_subscription
    redirect_to root_url if authenticate_school_subscription
  end

  def school_subscription_params
    params.require(:school_subscription).permit(
      %i[
        contact_email
        contact_name
        billing_name
        billing_address
        billing_city
        billing_postcode
        billing_brincode
        school_id
        user_id
      ]
    )
  end
end

app/views/subscriptions/_form.html.slim
.text-center.leading-7
  - if current_user.trial.active?
    .mb-6= t('activate_subscription.intro_html')

  h1.text-xl.mb-4.text-wz-black= t('activate_subscription.title')

  ul.mb-8.pl-8.text-left
    - t('activate_subscription.subscription_perks').each do |perk|
      li.flex.mb-2
        span.mr-2.mt-1= render(IconComponent.new(icon: "checkmark", size: "tiny"))
        span= perk

  h2.text-xl.text-wz-black.mb-2= t('activate_subscription.pricing', amount: localized_subscription_amount)
  - if current_user.trial.active?
    p
      = "#{t('activate_subscription.payment_starts_after_trial_ends')}:"
      br
      = current_user.localized_trail_period_expired_from

  .mt-4
    = button_to t('activate_subscription.cta_activate'), subscription_path, method: method, class: 'btn btn-cta mb-3 w-full'
    - if current_user.trial.active?
      = link_to t('activate_subscription.back_to_my_free_trial'), root_path, class: 'btn btn-light btn-border mb-3 w-full'
    .text-xs
      p.-mb-2= t('you_can_cancel_anytime')
      = link_to(t('login_as_a_different_user'), destroy_user_session_path, method: Rails.application.config.devise.sign_out_via, class: 'link')

app/views/subscriptions/invite.html.slim
= render(Page::Bare::Component.new) do |page|
  h1.text-xl.mb-5.text-wz-black= t('activate_subscription.school_subscription_agreement')
  p= t('activate_subscription.school_subscription_invoicing').html_safe
  h4= t('activate_subscription.invoicing_details')
  - flash.each do |_type, message|
    h1.text-xl.text-center.mb-5.text-wz-black= message

app/views/subscriptions/new.html.slim
= render(Page::Bare::Component.new) do |page|
  - flash.each do |_type, message|
    h1.text-xl.text-center.mb-5.text-wz-black= message

  = render 'form', method: :post

app/views/subscriptions/new_school.html.slim
= render(Page::Bare::Component.new) do |page|
  h1.text-xl.mb-5.text-wz-black.text-center
    = t('activate_subscription.school_subscription_agreement')
  div.text-center 
    = t('activate_subscription.school_subscription_invoicing').html_safe
  h4.py-8 = t('activate_subscription.invoicing_details')
  - flash.each do |_type, message|
    h1.text-xl.text-center.mb-5.text-wz-black= message
  = simple_form_for(@school_subscription, url: create_school_subscription_path(locale: I18n.locale)) do |f|
    = f.input :contact_email, autofocus: true
    = f.input :contact_name
    = f.input :billing_name
    = f.input :billing_brincode
    = f.input :billing_address
    = f.input :billing_city
    = f.input :billing_postcode
    = f.hidden_field :school_id
    = f.hidden_field :user_id

    .text-sm
      = t( \
        'sign_up_disclaimer_html', \
        sign_up: t('sign_up').capitalize,
        privacy_policy_link: external_link_to(:privacy_policy, class: 'link'), \
        terms_of_service_link: external_link_to(:terms_of_use, class: 'link') \
      )

    .mt-8
      = f.button :submit, t('activate_subscription.cta_specific_activate_text_only', subscriptionType: 'SCHOOL'), class: 'btn-cta w-full text-xs md:text-sm'
  p.text-center.text-sm.text-blue-600.mt-2
    = t('activate_subscription.student_amount_limit', studentLimit: '400') 
    = ' '
    = t('activate_subscription.anual_pricing', amount: localized_school_subscription_amount)

app/views/subscriptions/show.html.slim
= render(Page::Bare::Component.new) do |page|
  h1.text-xl.mb-8.text-wz-black= t('verifying_your_payment').capitalize

  = link_to t('try_again').capitalize, root_path, class: 'btn btn-cta w-full'

app/views/subscriptions/teacher_options.html.slim
= render(Page::Bare::Component.new) do |page|
    - if current_user.trial.active?
        p.text-wz-gray-600.text-lg.text-center
            = t('activate_subscription.school_subscription_description')

    h3.text-black.text-lg.text-center.centered.font-bold.pt-8
        = t('activate_subscription.school_subscription_cta')
    div.text-wz-gray-600.text-md.pt-8
        - t('activate_subscription.school_subscription_perks').each do |perk|
            li.flex.mb-2
                span.mr-2.mt-1= render(IconComponent.new(icon: "checkmark", size: "tiny"))
                span= perk
    div.text-wz-gray-600.text-md.text-center.py-4
        - if current_user.trial.active?
            = t('activate_subscription.subscribe_before_trial', endDate: I18n.l(current_user.trial&.expires_after, format: :long)).html_safe
    div.pb-8
        p.centered
            = link_to t('activate_subscription.cta_specific_activate', subscriptionType: t('class').upcase).html_safe, subscription_path, method: 'post', class: 'btn btn-cta mb-3 w-full'
            p.text-wz-light-blue-600.text-center
                span.pr-2.text-sm = t('activate_subscription.student_amount_limit', studentLimit: '35')
            p.text-wz-light-blue-600.text-center
                b.text-md = t('activate_subscription.pricing', amount: localized_class_subscription_amount)
            p.text-wz-light-blue-600.text-center.text-sm
                = t('you_can_cancel_anytime')
    p.centered
        = render('shared/button', label: t('activate_subscription.cta_specific_activate', subscriptionType: 'SCHOOL').html_safe, url: new_school_subscription_url)
        p.text-wz-light-blue-600.text-center
            span.pr-2.text-sm = t('activate_subscription.student_amount_limit', studentLimit: '400')
        p.text-wz-light-blue-600.text-center
            b.text-md = t('activate_subscription.anual_pricing', amount: localized_school_subscription_amount)
        p.text-wz-light-blue-600.text-center.text-sm
            = t('you_can_cancel_anually')


        p.centered.pt-8
            - if current_user.trial.active?
                = link_to t('activate_subscription.back_to_my_free_trial'), root_path, class: 'btn btn-light btn-border mb-3 w-full'
        p.text-wz-light-blue-600.text-center.text-xs.mt-2
            = link_to(t('login_as_a_different_user'), destroy_user_session_path, method: Rails.application.config.devise.sign_out_via, class: 'link')